build:
	# 这里改为剥离src/bin下的二进制文件
	# cargo build --release && \
	# rust-objcopy --strip-all target/riscv64gc-unknown-none-elf/release/rrcore -O binary target/riscv64gc-unknown-none-elf/release/rrcore.bin
